= Vault
include::_attributes.adoc[]

[#vaultk8s]
== Vault inside Kubernetes and secrets

The default way to install Vault inside Kubernetes is by using the official Vault chart developed at https://github.com/hashicorp/vault-helm[Vault Helm].

For this workshop, _dev mode_ is used.
This mode requires no further setup, the Vault is unsealed, no HTTPS and all the storage occurs in-memory among other simplifications.
This mode is perfect for experimentation.

WARNING: Never use _dev mode_ in production as it is unsecured by default.

=== Install Vault

Vault is installed into Kubernetes using a helm chart that is located at https://github.com/hashicorp/vault-helm.
To avoid having you to download the chart and install helm, a default `YAML` file produced by running `helm template vault --set='server.dev.enabled=true' -n default .` is provided in the repo.

With Minikube up and running, run the next command from a terminal window:

[source, shell-session]
----
kubectl apply -f $TUTORIAL_HOME/scripts/vault-dev-deployment.yml

serviceaccount/vault-agent-injector created // <1>
serviceaccount/vault created
clusterrole.rbac.authorization.k8s.io/vault-agent-injector-clusterrole created // <2>
clusterrolebinding.rbac.authorization.k8s.io/vault-agent-injector-binding created
clusterrolebinding.rbac.authorization.k8s.io/vault-server-binding created
service/vault-agent-injector-svc created
service/vault created
deployment.apps/vault-agent-injector created
statefulset.apps/vault created
mutatingwebhookconfiguration.admissionregistration.k8s.io/vault-agent-injector-cfg created
----
<1> Two service accounts are created.
<2> Cluster Role created to access Kubernetes API

=== Configure Vault

You need to configure Vault with a policy, a role to link with the policy and enable and configure the Kubernetes authentication method so our service can be authenticated automatically to Vault instead of relaying to a username/password.

.Kubernetes Authentication Method
****
(image)
****

Let's execute some commands inside the Vault container.
Normally, you would do these steps from outside, but to avoid the advanced setup in your local machine:

:podname: vault-0
include::partial$exec_pod.adoc[]

==== Create the policy

Create a policy that allows anyone logged in Vault to read any secret.
This could be limited by setting a more restricted expression in the `path` section.

[source, shell-session]
----
cat <<EOF > /home/vault/app-policy.hcl
path "secret*" {
  capabilities = ["read"]
}
EOF
----

Then create the policy called `vaultapp` and assign it to the previous policy:

[source, shell-session]
----
vault policy write vaultapp /home/vault/app-policy.hcl

Success! Uploaded policy: vaultapp
----

==== Kubernetes auth

The next thing to do is to enable and configure the Kubernetes auth method which allows our services to authenticate to Vault service without having to provide any username or password.

[source, shell-session]
----
vault auth enable kubernetes

Success! Enabled kubernetes auth method at: kubernetes/
----

The next step is configuring Kubernetes Auth method so it can communicate with Kubernetes API.

[source, shell-session]
----
vault write auth/kubernetes/config \
   token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
   kubernetes_host=https://${KUBERNETES_PORT_443_TCP_ADDR}:443 \
   kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt

Success! Data written to: auth/kubernetes/config
----

Finally, connect the Kubernetes auth method with the previously created policy and the service account created when our service is deployed (seen later).

[source, shell-session]
----
vault write auth/kubernetes/role/myapprole \
   bound_service_account_names=app \
   bound_service_account_namespaces=default \
   policies=vaultapp \
   ttl=24h

Success! Data written to: auth/kubernetes/role/myapprole
----

Things important to notice here:

. `myapprole` is a role for the service automatically logged to using this mechanism. Our service must be aware of it, and you need to set it on Vault client (seen later).
. `app` is a Kubernetes service account created in the deployment file.
. `vaultapp` is the policy created previously.

==== Create secret

To create a secret just run the next command:

[source, shell-session]
----
vault kv put secret/myapps/vault-service/config weather-api=123456

Key              Value
---              -----
created_time     2020-02-26T10:38:49.295513428Z
deletion_time    n/a
destroyed        false
version          1
----

Then you can exit to get back to your host machine:

[source, shell-session]
----
exit
----

[#deployapp]
== Deploy an application

Now, it is time to deploy an application that authenticates against Vault automatically using the Kubernetes auth mode, and takes the secret that you created in the previous section from the Vault service.

For this example, the service is developed using  https://quarkus.io/[Quarkus] but any other framework might offer similar API.

Deploy the service by running:

[source, shell-session]
----
kubectl apply -f $TUTORIAL_HOME/kubernetes/deploy-service.yml

deployment.apps/app created
serviceaccount/app created // <1>
service/vault-service-demo created
----
<1> The service account is created with the same name as set in the `bound_service_account_names` attribute when configuring Kubernetes auth.

include::partial$port_forward_service.adoc[]

Then in a terminal run the REST call which returns the secret stored in Vault:

[source, shell-session]
----
http :8080/secrets/weatherApi
HTTP/1.1 200 OK
Content-Length: 6
Content-Type: text/plain;charset=UTF-8

123456
----

=== Under the scenes

All the code is available at `$TUTORIAL_HOME/services/vault-started`.

The important bits of the code are the REST API resource, the configuration file, and the Vault dependency.

The configuration file is:

[source, properties]
.src/main/resources/application.properties
----
include::example$application.properties[]
----
<1> Vault server location.
<2> Secrets location. This value was used when creating the secret in Vault.
<3> The role created when configuring the Kubernetes auth.

The REST API resource is:

[source, java]
.src/main/java/org/acme/quickstart/SecretsResource.java
----
include::example$SecretsResource.java[tags=vault, indent=0]
----
<1> The value of the key with name `weather-api` is injected.

Apart from default Quarkus dependencies, the next dependency must be added:

[source, xml]
----
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-vault</artifactId>
</dependency>
----

When the Quarkus application is started, Vault extension authenticates using the Kubernetes auth method, and then it queries the Vault server to get the required secrets and inject them in the resource.

=== Recap

* [x] Vault can be used to manage secrets.
* [x] Quarkus integrates perfectly to get secrets from Vault in a declerative or programmatic way.
* [x] Kubernetes Auth method is sused to authenticate a service against a Vault server without requiring any secret like a password.

[#transit]
== Transit

Transit mode can be used from your application to encrypt and decrypt data.
You can think of this as cryptography as a service.

=== Configure Vault for transit

Let's execute some commands inside the Vault container.
Normally, you would do these steps from outside, but to avoid the advanced setup in your local machine:

:podname: vault-0
include::partial$exec_pod.adoc[]

==== Enable transit mode

[source, shell-session]
----
vault secrets enable transit

Success! Enabled the transit secrets engine at: transit/
----

==== Configure transit mode

To configure the transit mode, you need to create a named encryption key, in the next case the encryption name is `my-encryption-key`:

[source, shell-session]
----
vault write -f transit/keys/my-encryption-key

Success! Data written to: transit/keys/my-encryption-key
----

Create a policy that provides access to it:

[source, shell-session]
----
cat <<EOF > /home/vault/transit-policy.hcl
path "transit/encrypt/my-encryption-key" {
  capabilities = [ "update" ]
}
path "transit/decrypt/my-encryption-key" {
  capabilities = [ "update" ]
}
EOF

vault policy write transitvaultapp /home/vault/transit-policy.hcl

Success! Uploaded policy: transitvaultapp
----

Update the role created previously with the new policy named `transitvaultapp`:

[source, shell-session]
----
vault write auth/kubernetes/role/myapprole \
   bound_service_account_names=app \
   bound_service_account_namespaces=default \
   policies=vaultapp,transitvaultapp \
   ttl=24h

Success! Data written to: auth/kubernetes/role/myapprole

exit
----

[#quarkustransit]
== Quarkus Transit

The Quarkus application deployed in the previous section already implements the logic to encrypt and decrypt in transit, so you don't need to deploy anything else new.

With previous application deployed, if you undeployed just execute <<Deploy an application>> again and with port-forwarding still running, you can execute the next command to encrypt data:

[source, shell-session]
----
echo 'aixa' | http POST :8080/secrets/encrypt Content-Type:text/plain Accept:text/plain

HTTP/1.1 200 OK
Content-Length: 53
Content-Type: text/plain;charset=UTF-8

vault:v1:KO97AjQArhE82U06SNzq3pHeGOA41YsQjCh6nAMnCP+o
----

Then you can decrypt the data by executing the next command:

[source, shell-session]
----
echo 'vault:v1:KO97AjQArhE82U06SNzq3pHeGOA41YsQjCh6nAMnCP+o' | http POST :8080/secrets/decrypt Content-Type:text/plain Accept:text/plain

HTTP/1.1 200 OK
Content-Length: 5
Content-Type: text/plain;charset=UTF-8

aixa
----

=== Under the scenes

Quarkus integrates with transit mode too.

The authentication method is still the same but other classes are used to encrypt/decrypt data.

[source, java]
.src/main/java/org/acme/quickstart/SecretsResource.java
----
include::example$SecretsResource.java[tags=transit, indent=0]
----
<1> `VaultTransitSecretEngine` is the main class for transit.
<2> Data is encrypted using the `my-encryption-key` key.
<3> Data is decrypted using the `my-encryption-key` key.

=== Recap

* [x] Transit mode is cryptography as a service.
* [x] Quarkus is able to encrypt/decrypt/sign/verify using a Vault server.

=== Clean-up

It is not necessary to undeploy anything, as the same services are needed in the next section.

But if you want to clean everything done in this section, you just need to undeploy everything.

include::partial$clean_vault_quarkus.adoc[]

[#notesquarkusvault]
== Final Notes about Quarkus Vault

Quarkus integrates with several of Vault features:

* Secrets
* Username/Password, AppRole, and Kubernetes authentication methods
* Dynamic secrets
* Transit
* Access Vault secrets programmatically

Links:

* https://quarkus.io/guides/vault
* https://quarkus.io/guides/vault-transit