---
apiVersion: "v1"
kind: "ServiceAccount"
metadata:
  labels:
    app: "greeting"
    version: "1.0-SNAPSHOT"
    group: "lordofthejars"
  name: "greeting"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: "greeting"
    version: "1.0-SNAPSHOT"
    group: "lordofthejars"
  name: "greeting"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "greeting"
      version: "1.0-SNAPSHOT"
      group: "lordofthejars"
  template:
    metadata:
      labels:
        app: "greeting"
        version: "1.0-SNAPSHOT"
        group: "lordofthejars"
    # tag::spec[]
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: USERNAME # <1>
          valueFrom:
            secretKeyRef:
              name: db-secret # <2>
              key: username # <3>
        image: "fedora:33"
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        imagePullPolicy: "IfNotPresent"
        name: "greeting"
        ports:
        - containerPort: 8080
          name: "http"
          protocol: "TCP"
      serviceAccount: "greeting"
    # end::spec[]